### PR TITLE
doc: linkify + fix incorrectly closed bracket + typo

### PR DESCRIPTION
**Pull request by sorawee**
This is a follow-up of cb6a7e88308d4f1f69b

### CODE REVIEW

**Comment by sorawee** [comment]
@rfindler I am not sure about the last bit (where I changed `text%` to `racket:text%`). Commit cb6a7e88308d4f1f69b has `text%` in the contract box, but has `racket:text<%>` in the margin note. Which one is correct?

**Comment by rfindler** [comment]
Either `racket:text%` or `racket:text<%>` is okay, I think. Maybe the best is to say `an object that implements @racket[racket:text<%>]`.

**Comment by sorawee** [comment]
Thanks, fixed. Does it look good to you now?

**Comment by samth** [comment]
Can we merge this?

**Pull request merged**
