### PR TITLE
update logo in lang config guidance dialog

### PR DESCRIPTION
**Pull request by thuttner**
Hello, 
I've updated the logo in the dialog of #404 
racketeer

### CODE REVIEW

**Comment by rfindler** [comment]
`todays-icon` will be `#f` on non-unix platforms, so I don't think that this works.

**Comment by thuttner** [comment]
That's right:( What's the way to go? Should I add a png version of the new logo to https://github.com/racket/icons? Or it there a possibility to draw svg's directly?

**Comment by rfindler** [comment]
I just pushed something: what do you think?   https://github.com/racket/drracket/commit/9cb6f437661e7c78ad3701fba656487fceb8f11c

**Comment by thuttner** [comment]
Look's good :+1:

**Comment by rfindler** [comment]
Thanks! And thanks for spotting the problem!

**Comment by thuttner** [comment]
It wasn't me. Thanks have to go to @spdegabrielle

**Pull request closed without merging**
