### PR TITLE
Fix debugger's interaction with `begin0` (Issue #19)

### PR DESCRIPTION
**Pull request by florence**
This commit should be merged into the release branch

### CODE REVIEW

**Comment by florence** [comment]
I didn't write any tests since none exist and this is a small change. I can conjure up a testing harness if it seems very important. (But that might not get done before the release)

**Comment by stamourv** [comment]
The change looks reasonable.

**Comment by florence** [comment]
@rfindler Pointed out that we already had a test case for this, so I added it.

**Comment by rfindler** [comment]
I pushed this.

https://github.com/racket/drracket/commit/335e43e07d044b7c060597fdbe099588ea4752dd

**Pull request closed without merging**
