### PR TITLE
Allow adding Debug button to #lang languages

### PR DESCRIPTION
**Pull request by mikesperber**
Fixes https://github.com/racket/htdp/issues/177

### CODE REVIEW

**Comment by soegaard** [comment]
@rfindler This PR seems to be forgotten?

**Comment by rfindler** [comment]
Thank you for the reminder @soegaard ! I did somehow miss this one. 

@mikesperber  I think that maybe changing [something around here](https://github.com/racket/htdp/blob/master/htdp-lib/htdp/bsl/reader.rkt#L28-L37) based on [these docs](https://docs.racket-lang.org/tools/lang-languages-customization.html#%28part._.Opting_.Out_of_.Standard_.Toolbar_.Buttons%29) is a better way to go. Does that not work?

**Comment by mikesperber** [comment]
> @mikesperber I think that maybe changing [something around here](https://github.com/racket/htdp/blob/master/htdp-lib/htdp/bsl/reader.rkt#L28-L37) based on [these docs](https://docs.racket-lang.org/tools/lang-languages-customization.html#%28part._.Opting_.Out_of_.Standard_.Toolbar_.Buttons%29) is a better way to go. Does that not work?

Yes: But that has this as a prerequisite.

**Comment by rfindler** [comment]
> > @mikesperber I think that maybe changing [something around here](https://github.com/racket/htdp/blob/master/htdp-lib/htdp/bsl/reader.rkt#L28-L37) based on [these docs](https://docs.racket-lang.org/tools/lang-languages-customization.html#%28part._.Opting_.Out_of_.Standard_.Toolbar_.Buttons%29) is a better way to go. Does that not work?
> 
> Yes: But that has this as a prerequisite.

When I change the quoted code to have these two lines:

```
    [(drscheme:opt-out-toolbar-buttons)
     '(macro-stepper)]
```

(instead of returning `#f` from that case), then I see a debug button and clicking on it seems to turn on the debugger. 

Can you please elaborate on what you tried and how it goes wrong that led you to want to make modifications to drracket itself here?

**Comment by mikesperber** [comment]
@rfindler Ah, you mean the bottom line of that snippet, not the top lines. (The docs you quote are almost impossible to find if you don't know about them beforehand.)

I was following the example of the syntax-check and stepper buttons - the top lines of the snippet.

Shouldn't those be done the same way?

**Comment by rfindler** [comment]
I'm still seeing two "Check Syntax" buttons in the teaching languages ASL with the current commit.

Screenshot 2024-09-12 at 3 56 48 PM

**Comment by shhyou** [comment]
Superseded by @mikesperber's racket/htdp#222.

**Pull request closed without merging**
