### PR TITLE
Avoid phase+space error.

### PR DESCRIPTION
**Pull request by samth**
Fixes http://drdr.racket-lang.org/57872/cs/racket/share/pkgs/drracket-test/tests/drracket/syncheck-test.rkt

cc @rfindler

### CODE REVIEW

**Comment by rfindler** [comment]
This doesn't really fix anything, per se. I'll merge it with a different commit message; hope that's okay.

**Comment by samth** [comment]
That's fine with me.

**Comment by rfindler** [comment]
Thanks, @samth ! Sorry to be slow here.

It also appears that won't completely quiesce drdr. Looks like something improved somewhere! (So a different test case in that file also fails.)

**Comment by rfindler** [comment]
Oops, I got it backwards. It actually appears to be a regression for this program:

```
#lang racket/base
(require (for-syntax racket/base))
(begin-for-syntax (local-require racket/list) first)
```

The arrow from racket/list to first went away at some point.

**Pull request closed without merging**
